name: clovery310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - xz
  - openjdk=21
  - cmake
  - cxx-compiler
  - make
  - curl
  - unzip
  - git
  - universal-ctags
  - compilers
  - libtool
  - automake
  - pkg-config
  - autoconf
  - matplotlib
  - pytest
  - jq
  - sqlite
  - pip
  - pip:
      - beautifulsoup4==4.15.0
      - GitPython==3.1.50
      - requests==2.34.2
      - tqdm==4.68.3
      - py-tlsh==5.0.0
      - regex==2026.5.9
      - websockets==10.4
