#!/usr/bin/env python3
"""QLoRA supervised fine-tuning for CVE vendor/product/version extraction.

The input is one JSONL file containing the merged gold and silver records.  Each
line must provide ``cve_id``, ``description``, and ``bindings`` in the same shape
as ``data/cve_bindings_merged-800-hardrule-v1.jsonl``.  Any top-level provenance
metadata is ignored.  In cross-validation mode, records are first split into
90% development and 10% locked test data using product-group-aware
stratification.  Only the development records participate in K-fold CV; the
locked test records are never evaluated by the CV run.

The model learns to emit only ``{"bindings": [...]}``; ``cve_id`` and the source
description should be copied from the NVD input by the later inference pipeline,
not regenerated by the model.

Single RTX 2080 Ti example::

    python scripts/train_qwen_cve_bindings.py \
      --data data/cve_bindings_merged-800-hardrule-v1.jsonl \
      --model Qwen/Qwen3-4B-Instruct-2507 \
      --output-dir models/qwen3-4b-cve-bindings-9to1

Seven-GPU DDP example (lower accumulation keeps the global batch reasonable)::

    torchrun --standalone --nproc-per-node=7 \
      scripts/train_qwen_cve_bindings.py \
      --data data/cve_bindings_merged-800-hardrule-v1.jsonl \
      --cv-folds 5 \
      --gradient-accumulation-steps 1

"""

from __future__ import annotations

import argparse
import gc
import hashlib
import importlib.metadata
import inspect
import json
import math
import os
import random
import re
import sys
import time
import warnings
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Sequence


DEFAULT_MODEL = "Qwen/Qwen3-4B-Instruct-2507"
CVE_ID_RE = re.compile(r"^CVE-\d{4}-\d{4,}$", re.IGNORECASE)
LORA_TARGET_MODULES = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj",
]

SYSTEM_PROMPT = """You extract affected software bindings from an NVD CVE description.
Return exactly one minified JSON object with the single top-level key \"bindings\". Do not add Markdown or explanations.

Each binding has this exact shape:
{"vendor":string|null,"product":string,"version_ranges":[{"start":string|null,"start_inclusive":boolean|null,"end":string|null,"end_inclusive":boolean|null}]}

Rules:
- Extract only bindings supported by the description; never invent a vendor, product, or version.
- Preserve the naming and normalization style represented by the training labels.
- An exact version uses the same start and end with both inclusive flags true.
- "before/prior to VERSION" has an exclusive end; "through/up to VERSION" has an inclusive end.
- A plain "PRODUCT VERSION" mention is exact unless an explicit range modifier applies.
- Versions joined only by commas, "and", or "or" are separate exact versions, not a continuous interval.
- A missing endpoint and its inclusive flag are both null.
- If a product is affected but no version is stated, include one range whose four values are null.
- Rejected, reserved, or otherwise non-vulnerability records have an empty bindings array.
- Keep multiple products and multiple disjoint version ranges separate as represented by the text."""


class DataValidationError(ValueError):
    """Raised when the merged supervision JSONL cannot be trained safely."""


@dataclass(frozen=True)
class VersionRange:
    start: str | None
    start_inclusive: bool | None
    end: str | None
    end_inclusive: bool | None


@dataclass(frozen=True)
class Binding:
    vendor: str | None
    product: str
    version_ranges: tuple[VersionRange, ...]


@dataclass(frozen=True)
class TrainingRecord:
    cve_id: str
    description: str
    bindings: tuple[Binding, ...]


@dataclass(frozen=True)
class CVFold:
    index: int
    train_records: tuple[TrainingRecord, ...]
    validation_records: tuple[TrainingRecord, ...]
    metadata: dict[str, Any]


class EncodedDataset:
    """Small map-style dataset accepted directly by Transformers Trainer."""

    def __init__(self, examples: list[dict[str, list[int]]]) -> None:
        self.examples = examples

    def __len__(self) -> int:
        return len(self.examples)

    def __getitem__(self, index: int) -> dict[str, list[int]]:
        return self.examples[index]


def _nullable_string(value: Any, field: str, line_no: int) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise DataValidationError(f"{line_no}행 {field}: null 또는 비어 있지 않은 문자열이어야 합니다.")
    return value.strip()


def _nullable_bool(value: Any, field: str, line_no: int) -> bool | None:
    if value is None or isinstance(value, bool):
        return value
    raise DataValidationError(f"{line_no}행 {field}: boolean 또는 null이어야 합니다.")


def _normalize_version_range(value: Any, line_no: int, prefix: str) -> VersionRange:
    if not isinstance(value, dict):
        raise DataValidationError(f"{line_no}행 {prefix}: object여야 합니다.")
    required = {"start", "start_inclusive", "end", "end_inclusive"}
    missing = required.difference(value)
    if missing:
        raise DataValidationError(f"{line_no}행 {prefix}: 필수 키 누락 {sorted(missing)}")

    start = _nullable_string(value["start"], f"{prefix}.start", line_no)
    end = _nullable_string(value["end"], f"{prefix}.end", line_no)
    start_inclusive = _nullable_bool(
        value["start_inclusive"], f"{prefix}.start_inclusive", line_no
    )
    end_inclusive = _nullable_bool(
        value["end_inclusive"], f"{prefix}.end_inclusive", line_no
    )
    if (start is None) != (start_inclusive is None):
        raise DataValidationError(
            f"{line_no}행 {prefix}: start와 start_inclusive는 함께 null이거나 함께 값이 있어야 합니다."
        )
    if (end is None) != (end_inclusive is None):
        raise DataValidationError(
            f"{line_no}행 {prefix}: end와 end_inclusive는 함께 null이거나 함께 값이 있어야 합니다."
        )
    return VersionRange(start, start_inclusive, end, end_inclusive)


def _normalize_binding(value: Any, line_no: int, index: int) -> Binding:
    prefix = f"bindings[{index}]"
    if not isinstance(value, dict):
        raise DataValidationError(f"{line_no}행 {prefix}: object여야 합니다.")
    required = {"vendor", "product", "version_ranges"}
    missing = required.difference(value)
    if missing:
        raise DataValidationError(f"{line_no}행 {prefix}: 필수 키 누락 {sorted(missing)}")

    vendor = _nullable_string(value["vendor"], f"{prefix}.vendor", line_no)
    product = _nullable_string(value["product"], f"{prefix}.product", line_no)
    if product is None:
        raise DataValidationError(f"{line_no}행 {prefix}.product: null일 수 없습니다.")
    ranges = value["version_ranges"]
    if not isinstance(ranges, list) or not ranges:
        raise DataValidationError(f"{line_no}행 {prefix}.version_ranges: 비어 있지 않은 array여야 합니다.")
    normalized_ranges = tuple(
        _normalize_version_range(item, line_no, f"{prefix}.version_ranges[{range_index}]")
        for range_index, item in enumerate(ranges)
    )
    return Binding(vendor, product, normalized_ranges)


def normalize_record(value: Any, line_no: int) -> TrainingRecord:
    if not isinstance(value, dict):
        raise DataValidationError(f"{line_no}행: JSON object여야 합니다.")
    missing = {"cve_id", "description", "bindings"}.difference(value)
    if missing:
        raise DataValidationError(f"{line_no}행: 필수 키 누락 {sorted(missing)}")

    cve_id = value["cve_id"]
    if not isinstance(cve_id, str) or not CVE_ID_RE.fullmatch(cve_id.strip()):
        raise DataValidationError(f"{line_no}행 cve_id 형식이 올바르지 않습니다: {cve_id!r}")
    description = value["description"]
    if not isinstance(description, str) or not description.strip():
        raise DataValidationError(f"{line_no}행 description이 비어 있습니다.")
    bindings = value["bindings"]
    if not isinstance(bindings, list):
        raise DataValidationError(f"{line_no}행 bindings는 array여야 합니다.")

    return TrainingRecord(
        cve_id=cve_id.strip().upper(),
        description=description.strip(),
        bindings=tuple(
            _normalize_binding(binding, line_no, index)
            for index, binding in enumerate(bindings)
        ),
    )


def load_records(path: Path) -> list[TrainingRecord]:
    if not path.is_file():
        raise DataValidationError(f"학습 JSONL을 찾을 수 없습니다: {path}")

    records: list[TrainingRecord] = []
    seen: dict[str, int] = {}
    with path.open("r", encoding="utf-8") as source:
        for line_no, line in enumerate(source, start=1):
            if not line.strip():
                continue
            try:
                raw = json.loads(line)
            except json.JSONDecodeError as exc:
                raise DataValidationError(f"{line_no}행 JSON 오류: {exc}") from exc
            record = normalize_record(raw, line_no)
            previous = seen.get(record.cve_id)
            if previous is not None:
                raise DataValidationError(
                    f"중복 cve_id {record.cve_id}: {previous}행과 {line_no}행"
                )
            seen[record.cve_id] = line_no
            records.append(record)

    if len(records) < 2:
        raise DataValidationError("train/test 분리를 위해 최소 2개의 고유 레코드가 필요합니다.")
    return records


def _binding_count_bucket(record: TrainingRecord) -> str:
    count = len(record.bindings)
    if count == 0:
        return "0"
    if count == 1:
        return "1"
    if count <= 3:
        return "2-3"
    return "4+"


def _description_length_bucket(record: TrainingRecord) -> str:
    length = len(record.description)
    if length <= 512:
        return "<=512"
    if length <= 1024:
        return "513-1024"
    if length <= 2048:
        return "1025-2048"
    return "2049+"


def _version_shape_bucket(record: TrainingRecord) -> str:
    if not record.bindings:
        return "empty-bindings"
    shapes: set[str] = set()
    for binding in record.bindings:
        for version_range in binding.version_ranges:
            start, end = version_range.start, version_range.end
            if start is None and end is None:
                shapes.add("no-version")
            elif (
                start is not None
                and start == end
                and version_range.start_inclusive is True
                and version_range.end_inclusive is True
            ):
                shapes.add("exact")
            elif start is None:
                shapes.add("upper")
            elif end is None:
                shapes.add("lower")
            else:
                shapes.add("bounded")
    return next(iter(shapes)) if len(shapes) == 1 else "mixed"


def record_stratum(record: TrainingRecord) -> tuple[str, str, str]:
    """Use model-relevant, tokenizer-independent buckets for split balance."""
    return (
        _binding_count_bucket(record),
        _description_length_bucket(record),
        _version_shape_bucket(record),
    )


def _normalized_group_product(product: str) -> str:
    compact = re.sub(r"[^A-Za-z0-9]+", "", product)
    if len(compact) <= 4:
        # Keep the case signature for short names so Cisco IOS and Apple iOS
        # do not collapse into the same group.
        return compact
    return compact.casefold()


def _description_group_fingerprint(description: str) -> str:
    normalized = " ".join(description.casefold().split())
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def record_group_keys(record: TrainingRecord) -> tuple[str, ...]:
    """Return leakage-prevention keys; shared keys form connected components."""
    keys = {
        f"product:{_normalized_group_product(binding.product)}"
        for binding in record.bindings
        if _normalized_group_product(binding.product)
    }
    # Exact duplicate descriptions must remain together even if labels differ.
    keys.add(f"description:{_description_group_fingerprint(record.description)}")
    return tuple(sorted(keys))


def make_record_groups(
    records: Sequence[TrainingRecord],
) -> tuple[list[list[TrainingRecord]], dict[str, str]]:
    """Build transitive product/duplicate-description connected components."""
    parents = list(range(len(records)))
    sizes = [1] * len(records)

    def find(index: int) -> int:
        while parents[index] != index:
            parents[index] = parents[parents[index]]
            index = parents[index]
        return index

    def union(left: int, right: int) -> None:
        left_root, right_root = find(left), find(right)
        if left_root == right_root:
            return
        if sizes[left_root] < sizes[right_root]:
            left_root, right_root = right_root, left_root
        parents[right_root] = left_root
        sizes[left_root] += sizes[right_root]

    owner_by_key: dict[str, int] = {}
    for index, record in enumerate(records):
        for key in record_group_keys(record):
            previous = owner_by_key.get(key)
            if previous is None:
                owner_by_key[key] = index
            else:
                union(index, previous)

    records_by_root: dict[int, list[TrainingRecord]] = {}
    keys_by_root: dict[int, set[str]] = {}
    for index, record in enumerate(records):
        root = find(index)
        records_by_root.setdefault(root, []).append(record)
        keys_by_root.setdefault(root, set()).update(record_group_keys(record))

    ordered_roots = sorted(
        records_by_root,
        key=lambda root: min(record.cve_id for record in records_by_root[root]),
    )
    groups: list[list[TrainingRecord]] = []
    group_by_cve: dict[str, str] = {}
    for root in ordered_roots:
        group = sorted(records_by_root[root], key=lambda record: record.cve_id)
        identity = "\n".join(
            [*(sorted(keys_by_root[root])), *(record.cve_id for record in group)]
        )
        group_id = "group-" + hashlib.sha256(identity.encode("utf-8")).hexdigest()[:16]
        groups.append(group)
        for record in group:
            group_by_cve[record.cve_id] = group_id
    return groups, group_by_cve


def _stratum_key(stratum: tuple[str, str, str]) -> str:
    return "|".join(stratum)


def make_stratified_group_partitions(
    records: Sequence[TrainingRecord], num_partitions: int, seed: int
) -> tuple[list[list[TrainingRecord]], dict[str, Any]]:
    """Greedily balance strata while never splitting a product component."""
    if num_partitions < 2:
        raise ValueError("num_partitions는 2 이상이어야 합니다.")
    if len(records) < num_partitions:
        raise DataValidationError(
            f"레코드 {len(records)}건보다 분할 단위 {num_partitions}가 큽니다."
        )

    groups, group_by_cve = make_record_groups(records)
    if len(groups) < num_partitions:
        raise DataValidationError(
            f"독립 product group {len(groups)}개보다 분할 단위 {num_partitions}가 큽니다."
        )

    total_strata: dict[tuple[str, str, str], int] = {}
    group_strata: list[dict[tuple[str, str, str], int]] = []
    for group in groups:
        counts: dict[tuple[str, str, str], int] = {}
        for record in group:
            stratum = record_stratum(record)
            counts[stratum] = counts.get(stratum, 0) + 1
            total_strata[stratum] = total_strata.get(stratum, 0) + 1
        group_strata.append(counts)

    rng = random.Random(seed)
    tie_breakers = list(range(len(groups)))
    rng.shuffle(tie_breakers)
    tie_priority = {group_index: order for order, group_index in enumerate(tie_breakers)}
    ordered_group_indices = sorted(
        range(len(groups)),
        key=lambda index: (
            -len(groups[index]),
            -max(group_strata[index].values()),
            tie_priority[index],
        ),
    )

    partitions: list[list[TrainingRecord]] = [[] for _ in range(num_partitions)]
    partition_groups: list[list[int]] = [[] for _ in range(num_partitions)]
    partition_totals = [0] * num_partitions
    partition_strata: list[dict[tuple[str, str, str], int]] = [
        {} for _ in range(num_partitions)
    ]
    fold_priority = list(range(num_partitions))
    rng.shuffle(fold_priority)
    fold_tie = {fold: order for order, fold in enumerate(fold_priority)}
    target_size = len(records) / num_partitions

    def assignment_delta(group_index: int, fold: int) -> tuple[float, int, int]:
        size = len(groups[group_index])
        before_size = partition_totals[fold]
        size_delta = (
            ((before_size + size - target_size) / max(target_size, 1.0)) ** 2
            - ((before_size - target_size) / max(target_size, 1.0)) ** 2
        )
        stratum_delta = 0.0
        for stratum, addition in group_strata[group_index].items():
            target = total_strata[stratum] / num_partitions
            before = partition_strata[fold].get(stratum, 0)
            denominator = max(target, 1.0)
            stratum_delta += (
                ((before + addition - target) / denominator) ** 2
                - ((before - target) / denominator) ** 2
            )
        return stratum_delta + size_delta, partition_totals[fold], fold_tie[fold]

    for group_index in ordered_group_indices:
        selected = min(
            range(num_partitions),
            key=lambda fold: assignment_delta(group_index, fold),
        )
        partitions[selected].extend(groups[group_index])
        partition_groups[selected].append(group_index)
        partition_totals[selected] += len(groups[group_index])
        for stratum, addition in group_strata[group_index].items():
            partition_strata[selected][stratum] = (
                partition_strata[selected].get(stratum, 0) + addition
            )

    for fold, partition in enumerate(partitions):
        random.Random(seed + 20_000 + fold).shuffle(partition)
    if any(not partition for partition in partitions):
        raise DataValidationError("비어 있는 stratified group partition이 생성되었습니다.")

    assigned_ids = [record.cve_id for partition in partitions for record in partition]
    expected_ids = [record.cve_id for record in records]
    if len(assigned_ids) != len(set(assigned_ids)) or set(assigned_ids) != set(expected_ids):
        raise RuntimeError("stratified group 배정 중 레코드 누락 또는 중복이 발생했습니다.")
    for group in groups:
        fold_ids = {
            fold
            for fold, partition in enumerate(partitions)
            if any(record.cve_id in {item.cve_id for item in partition} for record in group)
        }
        if len(fold_ids) != 1:
            raise RuntimeError("동일 product group이 여러 partition으로 분리되었습니다.")

    metadata = {
        "scheme": "stratified_product_group_partitions",
        "seed": seed,
        "num_partitions": num_partitions,
        "stratify_by": [
            "binding_count",
            "description_length",
            "version_range_shape",
        ],
        "group_by": [
            "normalized_product_connected_components",
            "exact_description_fingerprint",
        ],
        "group_count": len(groups),
        "largest_group_size": max(len(group) for group in groups),
        "partition_counts": [len(partition) for partition in partitions],
        "partition_group_counts": [len(items) for items in partition_groups],
        "partition_empty_binding_counts": [
            sum(not record.bindings for record in partition)
            for partition in partitions
        ],
        "partition_stratum_counts": [
            {
                _stratum_key(stratum): count
                for stratum, count in sorted(counts.items())
            }
            for counts in partition_strata
        ],
        "group_by_cve": group_by_cve,
    }
    return partitions, metadata


def make_stratified_partitions(
    records: Sequence[TrainingRecord], num_partitions: int, seed: int
) -> list[list[TrainingRecord]]:
    """Create deterministic partitions balanced by binding count and text length."""
    if num_partitions < 2:
        raise ValueError("num_partitions는 2 이상이어야 합니다.")
    if len(records) < num_partitions:
        raise DataValidationError(
            f"레코드 {len(records)}건보다 분할 단위 {num_partitions}가 큽니다."
        )

    strata: dict[tuple[str, str], list[TrainingRecord]] = {}
    for record in sorted(records, key=lambda item: item.cve_id):
        strata.setdefault(record_stratum(record), []).append(record)

    rng = random.Random(seed)
    partitions: list[list[TrainingRecord]] = [[] for _ in range(num_partitions)]
    totals = [0] * num_partitions
    # Large strata go first. Each stratum is kept within one record per
    # partition, while total size resolves ties between equal candidates.
    ordered_strata = sorted(strata.items(), key=lambda item: (-len(item[1]), item[0]))
    for _, group in ordered_strata:
        group = list(group)
        rng.shuffle(group)
        stratum_counts = [0] * num_partitions
        tie_priority = list(range(num_partitions))
        rng.shuffle(tie_priority)
        priority = {partition: order for order, partition in enumerate(tie_priority)}
        for record in group:
            selected = min(
                range(num_partitions),
                key=lambda partition: (
                    stratum_counts[partition],
                    totals[partition],
                    priority[partition],
                ),
            )
            partitions[selected].append(record)
            stratum_counts[selected] += 1
            totals[selected] += 1

    for partition in partitions:
        rng.shuffle(partition)
    if any(not partition for partition in partitions):
        raise DataValidationError("비어 있는 train/test 분할 단위가 생성되었습니다.")

    assigned_ids = [record.cve_id for partition in partitions for record in partition]
    expected_ids = [record.cve_id for record in records]
    if len(assigned_ids) != len(set(assigned_ids)) or set(assigned_ids) != set(expected_ids):
        raise RuntimeError("train/test 배정 중 레코드 누락 또는 중복이 발생했습니다.")
    return partitions


def split_train_test(
    records: Sequence[TrainingRecord],
    split_ratio: tuple[int, int],
    seed: int,
) -> tuple[list[TrainingRecord], list[TrainingRecord], dict[str, Any]]:
    """Create one fixed stratified train/test split."""
    train_units, test_units = split_ratio
    total_units = sum(split_ratio)
    partitions = make_stratified_partitions(records, total_units, seed)
    train = [
        record for partition in partitions[:train_units] for record in partition
    ]
    test = [record for partition in partitions[train_units:] for record in partition]
    random.Random(seed + 10_001).shuffle(train)
    random.Random(seed + 10_002).shuffle(test)

    train_ids = {record.cve_id for record in train}
    test_ids = {record.cve_id for record in test}
    if not train or not test:
        raise DataValidationError("train/test 중 비어 있는 split이 있습니다.")
    if train_ids.intersection(test_ids):
        raise RuntimeError("train/test 사이에 CVE ID 누수가 있습니다.")
    if train_ids.union(test_ids) != {record.cve_id for record in records}:
        raise RuntimeError("train/test 분할 중 레코드 누락이 발생했습니다.")

    metadata = {
        "scheme": "stratified_train_test",
        "ratio": {"train": train_units, "test": test_units},
        "seed": seed,
        "stratify_by": ["binding_count", "description_length"],
        "counts": {"train": len(train), "test": len(test)},
        "empty_binding_counts": {
            "train": sum(not record.bindings for record in train),
            "test": sum(not record.bindings for record in test),
        },
    }
    return train, test, metadata


def split_development_test_grouped(
    records: Sequence[TrainingRecord],
    split_ratio: tuple[int, int],
    seed: int,
) -> tuple[list[TrainingRecord], list[TrainingRecord], dict[str, Any]]:
    """Create a locked test split without product-group leakage."""
    development_units, test_units = split_ratio
    partitions, partition_metadata = make_stratified_group_partitions(
        records, sum(split_ratio), seed
    )
    development = [
        record
        for partition in partitions[:development_units]
        for record in partition
    ]
    locked_test = [
        record
        for partition in partitions[development_units:]
        for record in partition
    ]
    random.Random(seed + 10_001).shuffle(development)
    random.Random(seed + 10_002).shuffle(locked_test)

    development_ids = {record.cve_id for record in development}
    test_ids = {record.cve_id for record in locked_test}
    if not development or not locked_test:
        raise DataValidationError("development/test 중 비어 있는 split이 있습니다.")
    if development_ids.intersection(test_ids):
        raise RuntimeError("development/test 사이에 CVE ID 누수가 있습니다.")
    group_by_cve = partition_metadata["group_by_cve"]
    development_groups = {group_by_cve[cve_id] for cve_id in development_ids}
    test_groups = {group_by_cve[cve_id] for cve_id in test_ids}
    if development_groups.intersection(test_groups):
        raise RuntimeError("development/test 사이에 product group 누수가 있습니다.")

    metadata = {
        "scheme": "stratified_product_group_development_test",
        "ratio": {"development": development_units, "test": test_units},
        "seed": seed,
        "counts": {
            "development": len(development),
            "locked_test": len(locked_test),
        },
        "empty_binding_counts": {
            "development": sum(not record.bindings for record in development),
            "locked_test": sum(not record.bindings for record in locked_test),
        },
        "partitioning": partition_metadata,
    }
    return development, locked_test, metadata


def make_cv_folds(
    development_records: Sequence[TrainingRecord],
    cv_folds: int,
    seed: int,
) -> tuple[list[CVFold], dict[str, Any]]:
    """Create K validation folds; every development record is OOF exactly once."""
    partitions, partition_metadata = make_stratified_group_partitions(
        development_records, cv_folds, seed + 30_000
    )
    expected_ids = {record.cve_id for record in development_records}
    folds: list[CVFold] = []
    validation_occurrences: Counter[str] = Counter()
    for fold_index in range(cv_folds):
        validation = list(partitions[fold_index])
        train = [
            record
            for index, partition in enumerate(partitions)
            if index != fold_index
            for record in partition
        ]
        random.Random(seed + 40_000 + fold_index).shuffle(train)
        random.Random(seed + 50_000 + fold_index).shuffle(validation)
        train_ids = {record.cve_id for record in train}
        validation_ids = {record.cve_id for record in validation}
        if train_ids.intersection(validation_ids):
            raise RuntimeError(f"CV fold {fold_index + 1}: train/validation ID 누수")
        if train_ids.union(validation_ids) != expected_ids:
            raise RuntimeError(f"CV fold {fold_index + 1}: 레코드 누락")
        group_by_cve = partition_metadata["group_by_cve"]
        train_groups = {group_by_cve[cve_id] for cve_id in train_ids}
        validation_groups = {group_by_cve[cve_id] for cve_id in validation_ids}
        if train_groups.intersection(validation_groups):
            raise RuntimeError(
                f"CV fold {fold_index + 1}: train/validation product group 누수"
            )
        validation_occurrences.update(validation_ids)
        folds.append(
            CVFold(
                index=fold_index + 1,
                train_records=tuple(train),
                validation_records=tuple(validation),
                metadata={
                    "fold_index": fold_index + 1,
                    "train_count": len(train),
                    "validation_count": len(validation),
                    "train_group_count": len(train_groups),
                    "validation_group_count": len(validation_groups),
                    "empty_binding_counts": {
                        "train": sum(not record.bindings for record in train),
                        "validation": sum(not record.bindings for record in validation),
                    },
                    "train_cve_ids": [record.cve_id for record in train],
                    "validation_cve_ids": [
                        record.cve_id for record in validation
                    ],
                },
            )
        )
    if set(validation_occurrences) != expected_ids or any(
        count != 1 for count in validation_occurrences.values()
    ):
        raise RuntimeError("각 development 레코드가 validation에 정확히 한 번 배정되지 않았습니다.")
    metadata = {
        "scheme": "stratified_product_group_kfold",
        "cv_folds": cv_folds,
        "seed": seed,
        "development_count": len(development_records),
        "fold_counts": [
            {
                "fold_index": fold.index,
                "train": len(fold.train_records),
                "validation": len(fold.validation_records),
            }
            for fold in folds
        ],
        "partitioning": partition_metadata,
    }
    return folds, metadata


def user_prompt(record: TrainingRecord) -> str:
    return f"CVE ID: {record.cve_id}\nDescription:\n{record.description}"


def target_json(record: TrainingRecord) -> str:
    payload = {
        "bindings": [
            {
                "vendor": binding.vendor,
                "product": binding.product,
                "version_ranges": [asdict(version_range) for version_range in binding.version_ranges],
            }
            for binding in record.bindings
        ]
    }
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def chat_template_ids(
    tokenizer: Any,
    messages: list[dict[str, str]],
    *,
    add_generation_prompt: bool,
) -> list[int]:
    """Return token IDs consistently across Transformers 4.x and 5.x.

    Transformers 5 changed ``apply_chat_template`` to return a BatchEncoding by
    default.  Requesting a dictionary and selecting ``input_ids`` explicitly
    avoids depending on that version-specific default.
    """
    result = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=add_generation_prompt,
        return_dict=True,
    )
    try:
        input_ids = result["input_ids"]
    except (KeyError, TypeError) as exc:
        raise RuntimeError("chat template 결과에 input_ids가 없습니다.") from exc
    if not isinstance(input_ids, list) or (
        input_ids and (isinstance(input_ids[0], bool) or not isinstance(input_ids[0], int))
    ):
        raise RuntimeError(
            "chat template의 input_ids가 단일 token ID 목록이 아닙니다. "
            "단일 conversation 입력인지 확인하세요."
        )
    return input_ids


def encode_records(
    records: Sequence[TrainingRecord], tokenizer: Any, max_seq_length: int
) -> tuple[list[dict[str, list[int]]], list[int]]:
    encoded: list[dict[str, list[int]]] = []
    lengths: list[int] = []
    overlength: list[tuple[str, int]] = []

    for record in records:
        prompt_messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt(record)},
        ]
        full_messages = [
            *prompt_messages,
            {"role": "assistant", "content": target_json(record)},
        ]
        prompt_ids = chat_template_ids(
            tokenizer, prompt_messages, add_generation_prompt=True
        )
        full_ids = chat_template_ids(
            tokenizer, full_messages, add_generation_prompt=False
        )
        if full_ids[: len(prompt_ids)] != prompt_ids:
            raise RuntimeError(
                "토크나이저 chat template에서 assistant 응답 경계를 찾지 못했습니다. "
                "Qwen3 Instruct tokenizer인지 확인하세요."
            )
        assistant_token_count = len(full_ids) - len(prompt_ids)
        if assistant_token_count <= 0:
            raise RuntimeError(f"assistant 학습 token이 없습니다: {record.cve_id}")

        length = len(full_ids)
        lengths.append(length)
        if length > max_seq_length:
            overlength.append((record.cve_id, length))
            continue
        encoded.append(
            {
                "input_ids": full_ids,
                "attention_mask": [1] * length,
                "labels": [-100] * len(prompt_ids) + full_ids[len(prompt_ids) :],
            }
        )

    if overlength:
        examples = ", ".join(
            f"{cve_id}={length}" for cve_id, length in sorted(overlength, key=lambda x: -x[1])[:10]
        )
        required = max(length for _, length in overlength)
        raise DataValidationError(
            f"{len(overlength)}건이 --max-seq-length {max_seq_length}를 초과합니다 "
            f"({examples}). 정답 JSON을 자르지 않도록 최소 {required} 이상으로 올리세요."
        )
    return encoded, lengths


def percentile(values: Sequence[int], probability: float) -> int:
    ordered = sorted(values)
    index = min(len(ordered) - 1, math.ceil(probability * len(ordered)) - 1)
    return ordered[index]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def package_version(name: str) -> str | None:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return None


def parse_version(value: str) -> tuple[int, ...]:
    numbers = re.match(r"^(\d+(?:\.\d+)*)", value)
    return tuple(int(part) for part in numbers.group(1).split(".")) if numbers else ()


def import_training_stack() -> dict[str, Any]:
    try:
        import torch
        import transformers
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            BitsAndBytesConfig,
            Trainer,
            TrainingArguments,
            set_seed,
        )
        from transformers.utils import logging as transformers_logging
    except ImportError as exc:
        raise RuntimeError(
            "학습 의존성이 없습니다. CUDA용 PyTorch를 설치한 환경에서 "
            "`pip install -U 'transformers>=4.51' accelerate peft bitsandbytes`를 실행하세요. "
            f"원인: {exc}"
        ) from exc

    if parse_version(transformers.__version__) < (4, 51):
        raise RuntimeError(
            f"Qwen3에는 transformers>=4.51이 필요합니다 (현재 {transformers.__version__})."
        )

    return {
        "torch": torch,
        "transformers_version": transformers.__version__,
        "LoraConfig": LoraConfig,
        "get_peft_model": get_peft_model,
        "prepare_model_for_kbit_training": prepare_model_for_kbit_training,
        "AutoModelForCausalLM": AutoModelForCausalLM,
        "AutoTokenizer": AutoTokenizer,
        "BitsAndBytesConfig": BitsAndBytesConfig,
        "Trainer": Trainer,
        "TrainingArguments": TrainingArguments,
        "set_seed": set_seed,
        "transformers_logging": transformers_logging,
    }


def make_chunked_causal_lm_loss(torch: Any, chunk_size: int):
    """Compute causal LM loss without a full float32 vocabulary-logit copy.

    Transformers' default causal loss casts every logit to float32 at once.
    Qwen3 has a vocabulary of roughly 152k tokens, so one 3,800-token example
    needs another ~2.2 GiB just for that cast.  Checkpointing each token chunk
    keeps the numerically stable float32 cross-entropy while bounding its peak
    memory; the chunk is recomputed during backward instead of being retained.
    """

    def chunked_loss(
        logits: Any,
        labels: Any,
        vocab_size: int,
        num_items_in_batch: Any = None,
        ignore_index: int = -100,
        **_: Any,
    ) -> Any:
        if logits.shape[-1] != vocab_size:
            raise RuntimeError(
                f"logit vocabulary 크기 불일치: {logits.shape[-1]} != {vocab_size}"
            )

        # logits_to_keep retains the suffix beginning one token before the
        # assistant answer.  Select the matching next-token labels.
        shifted = torch.nn.functional.pad(labels, (0, 1), value=ignore_index)
        shifted = shifted[..., -logits.shape[-2] :].contiguous()
        flat_logits = logits.reshape(-1, vocab_size)
        flat_labels = shifted.reshape(-1).to(logits.device)

        def cross_entropy_sum(logit_chunk: Any, label_chunk: Any) -> Any:
            return torch.nn.functional.cross_entropy(
                logit_chunk.float(),
                label_chunk,
                ignore_index=ignore_index,
                reduction="sum",
            )

        parts: list[Any] = []
        for start in range(0, flat_logits.shape[0], chunk_size):
            logit_chunk = flat_logits[start : start + chunk_size]
            label_chunk = flat_labels[start : start + chunk_size]
            if torch.is_grad_enabled() and logit_chunk.requires_grad:
                part = torch.utils.checkpoint.checkpoint(
                    cross_entropy_sum,
                    logit_chunk,
                    label_chunk,
                    use_reentrant=True,
                )
            else:
                part = cross_entropy_sum(logit_chunk, label_chunk)
            parts.append(part)

        if not parts:
            raise RuntimeError("loss를 계산할 token이 없습니다.")
        total = torch.stack(parts).sum()
        if num_items_in_batch is not None:
            denominator = num_items_in_batch.to(total.device) if torch.is_tensor(
                num_items_in_batch
            ) else num_items_in_batch
        else:
            denominator = (flat_labels != ignore_index).sum().clamp_min(1)
        return total / denominator

    return chunked_loss


def evaluate_test_metrics(
    *,
    torch: Any,
    model: Any,
    encoded_test: Sequence[dict[str, list[int]]],
    data_collator: Any,
    device: Any,
    rank: int,
    world_size: int,
    batch_size: int,
) -> dict[str, float | int]:
    """Evaluate unique test shards before any cross-rank sequence padding.

    Transformers pads variable-length logits on the right *before* calling
    ``preprocess_logits_for_metrics``.  Our logits contain only the assistant
    suffix, so aligning those padded suffixes against independently padded full
    labels shifts token positions across DDP ranks.  Instead, each rank reduces
    its unpadded local logits to scalar counts and only those counts are summed.
    """
    local_examples = list(encoded_test[rank::world_size])

    distributed = (
        torch.distributed.is_available() and torch.distributed.is_initialized()
    )
    if distributed:
        torch.distributed.barrier(device_ids=[device.index])
    torch.cuda.synchronize(device)
    started_at = time.perf_counter()

    # loss sum, correct tokens, supervised tokens, exact records, records
    totals = torch.zeros(5, dtype=torch.float64, device=device)
    model.eval()
    with torch.inference_mode():
        for start in range(0, len(local_examples), batch_size):
            features = local_examples[start : start + batch_size]
            batch = data_collator(features)
            batch = {
                key: value.to(device) if torch.is_tensor(value) else value
                for key, value in batch.items()
            }
            labels = batch["labels"]
            outputs = model(**batch)
            logits = outputs.logits

            ignore_index = -100
            shifted = torch.nn.functional.pad(labels, (0, 1), value=ignore_index)
            shifted = shifted[..., -logits.shape[-2] :].to(logits.device)
            supervised = shifted.ne(ignore_index)
            correct = logits.argmax(dim=-1).eq(shifted) & supervised
            correct_per_record = correct.sum(dim=-1)
            tokens_per_record = supervised.sum(dim=-1)
            if not tokens_per_record.gt(0).all():
                raise RuntimeError("test batch에 정답 assistant token이 없는 record가 있습니다.")

            token_count = tokens_per_record.sum()
            totals[0] += outputs.loss.detach().to(torch.float64) * token_count
            totals[1] += correct_per_record.sum()
            totals[2] += token_count
            totals[3] += correct_per_record.eq(tokens_per_record).sum()
            totals[4] += labels.shape[0]

    torch.cuda.synchronize(device)
    elapsed = torch.tensor(
        time.perf_counter() - started_at, dtype=torch.float64, device=device
    )
    if distributed:
        torch.distributed.all_reduce(totals, op=torch.distributed.ReduceOp.SUM)
        torch.distributed.all_reduce(elapsed, op=torch.distributed.ReduceOp.MAX)

    loss_sum, correct_tokens, supervised_tokens, exact_records, record_count = (
        totals.tolist()
    )
    if supervised_tokens <= 0 or record_count <= 0:
        raise RuntimeError("test metric을 계산할 정답 token 또는 record가 없습니다.")
    expected_records = len(encoded_test)
    if int(record_count) != expected_records:
        raise RuntimeError(
            f"test 집계 record 수 불일치: {int(record_count)} != {expected_records}"
        )

    runtime = elapsed.item()
    max_steps_per_rank = math.ceil(
        math.ceil(expected_records / world_size) / batch_size
    )
    return {
        "test_loss": loss_sum / supervised_tokens,
        "test_accuracy": correct_tokens / supervised_tokens,
        "test_teacher_forced_exact_match": exact_records / record_count,
        "test_correct_tokens": int(correct_tokens),
        "test_supervised_tokens": int(supervised_tokens),
        "test_exact_match_count": int(exact_records),
        "test_samples": int(record_count),
        "test_runtime": runtime,
        "test_samples_per_second": record_count / runtime,
        "test_steps_per_second": max_steps_per_rank / runtime,
    }


def validate_generated_bindings_payload(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict) or set(payload) != {"bindings"}:
        raise ValueError('최상위 JSON은 단일 키 "bindings"만 가져야 합니다.')
    if not isinstance(payload["bindings"], list):
        raise ValueError("bindings가 array가 아닙니다.")
    normalized_bindings: list[dict[str, Any]] = []
    for binding_index, binding in enumerate(payload["bindings"]):
        prefix = f"bindings[{binding_index}]"
        if not isinstance(binding, dict) or set(binding) != {
            "vendor",
            "product",
            "version_ranges",
        }:
            raise ValueError(f"{prefix}: 필드 구성이 올바르지 않습니다.")
        vendor, product = binding["vendor"], binding["product"]
        if vendor is not None and not isinstance(vendor, str):
            raise ValueError(f"{prefix}.vendor: string 또는 null이어야 합니다.")
        if not isinstance(product, str) or not product:
            raise ValueError(f"{prefix}.product가 비어 있거나 string이 아닙니다.")
        raw_ranges = binding["version_ranges"]
        if not isinstance(raw_ranges, list) or not raw_ranges:
            raise ValueError(f"{prefix}.version_ranges가 비어 있습니다.")
        normalized_ranges: list[dict[str, Any]] = []
        for range_index, version_range in enumerate(raw_ranges):
            range_prefix = f"{prefix}.version_ranges[{range_index}]"
            if not isinstance(version_range, dict) or set(version_range) != {
                "start",
                "start_inclusive",
                "end",
                "end_inclusive",
            }:
                raise ValueError(f"{range_prefix}: 필드 구성이 올바르지 않습니다.")
            for endpoint in ("start", "end"):
                inclusive = f"{endpoint}_inclusive"
                value = version_range[endpoint]
                flag = version_range[inclusive]
                if value is not None and not isinstance(value, str):
                    raise ValueError(f"{range_prefix}.{endpoint}: string/null 필요")
                if flag is not None and not isinstance(flag, bool):
                    raise ValueError(f"{range_prefix}.{inclusive}: boolean/null 필요")
                if (value is None) != (flag is None):
                    raise ValueError(
                        f"{range_prefix}: {endpoint}와 {inclusive}는 함께 null이어야 합니다."
                    )
            normalized_ranges.append(
                {
                    "start": version_range["start"],
                    "start_inclusive": version_range["start_inclusive"],
                    "end": version_range["end"],
                    "end_inclusive": version_range["end_inclusive"],
                }
            )
        normalized_bindings.append(
            {
                "vendor": vendor,
                "product": product,
                "version_ranges": normalized_ranges,
            }
        )
    return {"bindings": normalized_bindings}


def canonical_generated_payload(
    payload: dict[str, Any], *, normalize_strings: bool
) -> tuple[Any, ...]:
    def normalize(value: Any) -> Any:
        if not normalize_strings or not isinstance(value, str):
            return value
        return re.sub(r"[^a-z0-9]+", "", value.casefold())

    bindings: list[tuple[Any, ...]] = []
    for binding in payload["bindings"]:
        ranges = [
            (
                normalize(version_range["start"]),
                version_range["start_inclusive"],
                normalize(version_range["end"]),
                version_range["end_inclusive"],
            )
            for version_range in binding["version_ranges"]
        ]
        bindings.append(
            (
                normalize(binding["vendor"]),
                normalize(binding["product"]),
                tuple(sorted(ranges, key=repr)),
            )
        )
    return tuple(sorted(bindings, key=repr))


def record_target_payload(record: TrainingRecord) -> dict[str, Any]:
    return json.loads(target_json(record))


def _eos_token_ids(tokenizer: Any, model: Any) -> set[int]:
    values = [
        tokenizer.eos_token_id,
        getattr(model.generation_config, "eos_token_id", None),
    ]
    result: set[int] = set()
    for value in values:
        if isinstance(value, int):
            result.add(value)
        elif isinstance(value, (list, tuple)):
            result.update(item for item in value if isinstance(item, int))
    return result


def evaluate_generation_metrics(
    *,
    torch: Any,
    model: Any,
    tokenizer: Any,
    records: Sequence[TrainingRecord],
    system_prompt: str,
    device: Any,
    rank: int,
    world_size: int,
    batch_size: int,
    max_new_tokens: int,
) -> tuple[dict[str, float | int], list[dict[str, Any]]]:
    """Run greedy free generation and gather OOF-ready per-record predictions."""
    local_items = list(enumerate(records))[rank::world_size]
    distributed = (
        torch.distributed.is_available() and torch.distributed.is_initialized()
    )
    if distributed:
        torch.distributed.barrier(device_ids=[device.index])
    torch.cuda.synchronize(device)
    started_at = time.perf_counter()
    eos_ids = _eos_token_ids(tokenizer, model)
    local_predictions: list[dict[str, Any]] = []
    # valid, strict, order-insensitive, normalized, records, generation-limit
    totals = torch.zeros(6, dtype=torch.float64, device=device)
    model.eval()
    original_use_cache = model.config.use_cache
    model.config.use_cache = True
    try:
        for batch_start in range(0, len(local_items), batch_size):
            batch_items = local_items[batch_start : batch_start + batch_size]
            prompt_ids = [
                chat_template_ids(
                    tokenizer,
                    [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt(record)},
                    ],
                    add_generation_prompt=True,
                )
                for _, record in batch_items
            ]
            max_prompt_length = max(len(ids) for ids in prompt_ids)
            padded_ids = [
                [tokenizer.pad_token_id] * (max_prompt_length - len(ids)) + ids
                for ids in prompt_ids
            ]
            attention_masks = [
                [0] * (max_prompt_length - len(ids)) + [1] * len(ids)
                for ids in prompt_ids
            ]
            with torch.inference_mode():
                sequences = model.generate(
                    input_ids=torch.tensor(
                        padded_ids, dtype=torch.long, device=device
                    ),
                    attention_mask=torch.tensor(
                        attention_masks, dtype=torch.long, device=device
                    ),
                    do_sample=False,
                    max_new_tokens=max_new_tokens,
                    pad_token_id=tokenizer.pad_token_id,
                    eos_token_id=tokenizer.eos_token_id,
                    use_cache=True,
                )
            for row, (evaluation_index, record) in enumerate(batch_items):
                generated_ids = sequences[row, max_prompt_length:].tolist()
                eos_position = next(
                    (
                        index
                        for index, token_id in enumerate(generated_ids)
                        if token_id in eos_ids
                    ),
                    None,
                )
                hit_limit = (
                    eos_position is None and len(generated_ids) >= max_new_tokens
                )
                content_ids = (
                    generated_ids
                    if eos_position is None
                    else generated_ids[:eos_position]
                )
                raw_output = tokenizer.decode(
                    content_ids, skip_special_tokens=True
                ).strip()
                gold = record_target_payload(record)
                prediction: dict[str, Any] | None = None
                error: str | None = None
                try:
                    prediction = validate_generated_bindings_payload(
                        json.loads(raw_output)
                    )
                except (json.JSONDecodeError, ValueError) as exc:
                    error = f"{type(exc).__name__}: {exc}"
                strict = prediction == gold if prediction is not None else False
                order_insensitive = (
                    canonical_generated_payload(
                        prediction, normalize_strings=False
                    )
                    == canonical_generated_payload(gold, normalize_strings=False)
                    if prediction is not None
                    else False
                )
                normalized = (
                    canonical_generated_payload(
                        prediction, normalize_strings=True
                    )
                    == canonical_generated_payload(gold, normalize_strings=True)
                    if prediction is not None
                    else False
                )
                totals[0] += prediction is not None
                totals[1] += strict
                totals[2] += order_insensitive
                totals[3] += normalized
                totals[4] += 1
                totals[5] += hit_limit
                local_predictions.append(
                    {
                        "evaluation_index": evaluation_index,
                        "cve_id": record.cve_id,
                        "description": record.description,
                        "gold": gold,
                        "prediction": prediction,
                        "raw_model_output": raw_output,
                        "status": (
                            "invalid_model_output"
                            if prediction is None
                            else "generation_limit"
                            if hit_limit
                            else "ok"
                        ),
                        "error": error,
                        "generated_tokens": len(content_ids),
                        "strict_exact": strict,
                        "order_insensitive_exact": order_insensitive,
                        "normalized_exact": normalized,
                    }
                )
    finally:
        model.config.use_cache = original_use_cache

    torch.cuda.synchronize(device)
    elapsed = torch.tensor(
        time.perf_counter() - started_at, dtype=torch.float64, device=device
    )
    if distributed:
        torch.distributed.all_reduce(totals, op=torch.distributed.ReduceOp.SUM)
        torch.distributed.all_reduce(elapsed, op=torch.distributed.ReduceOp.MAX)
        gathered: list[Any] = [None] * world_size
        torch.distributed.all_gather_object(gathered, local_predictions)
        all_predictions = [
            prediction for rank_items in gathered for prediction in rank_items
        ]
    else:
        all_predictions = local_predictions

    valid, strict, order_insensitive, normalized, sample_count, limits = (
        totals.tolist()
    )
    if int(sample_count) != len(records):
        raise RuntimeError(
            f"generation 평가 record 수 불일치: {int(sample_count)} != {len(records)}"
        )
    runtime = elapsed.item()
    all_predictions.sort(key=lambda item: item["evaluation_index"])
    metrics: dict[str, float | int] = {
        "generation_valid_rate": valid / sample_count,
        "generation_strict_exact_match": strict / sample_count,
        "generation_order_insensitive_exact_match": (
            order_insensitive / sample_count
        ),
        "generation_normalized_exact_match": normalized / sample_count,
        "generation_valid_count": int(valid),
        "generation_strict_exact_count": int(strict),
        "generation_order_insensitive_exact_count": int(order_insensitive),
        "generation_normalized_exact_count": int(normalized),
        "generation_limit_count": int(limits),
        "generation_samples": int(sample_count),
        "generation_runtime": runtime,
        "generation_samples_per_second": sample_count / runtime,
    }
    return metrics, all_predictions if rank == 0 else []


def make_collator(torch: Any, pad_token_id: int):
    def collate(features: list[dict[str, list[int]]]) -> dict[str, Any]:
        max_length = max(len(feature["input_ids"]) for feature in features)
        max_length = math.ceil(max_length / 8) * 8
        input_ids: list[list[int]] = []
        attention_masks: list[list[int]] = []
        labels: list[list[int]] = []
        for feature in features:
            padding = max_length - len(feature["input_ids"])
            input_ids.append(feature["input_ids"] + [pad_token_id] * padding)
            attention_masks.append(feature["attention_mask"] + [0] * padding)
            labels.append(feature["labels"] + [-100] * padding)
        batch = {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_masks, dtype=torch.long),
            "labels": torch.tensor(labels, dtype=torch.long),
        }
        supervised = batch["labels"].ne(-100)
        if not supervised.any():
            raise RuntimeError("batch에 assistant 학습 token이 없습니다.")
        first_supervised = supervised.nonzero(as_tuple=False)[:, 1].min().item()
        # Keep the logit immediately before the first supervised token through
        # the end.  That preceding logit predicts the first assistant token.
        batch["logits_to_keep"] = max_length - first_supervised + 1
        return batch

    return collate


def ensure_output_is_safe(args: argparse.Namespace) -> None:
    output = args.output_dir
    if output.exists() and not output.is_dir():
        raise DataValidationError(f"출력 경로가 디렉터리가 아닙니다: {output}")
    if args.resume_from_checkpoint is not None and not args.resume_from_checkpoint.is_dir():
        raise DataValidationError(
            f"resume checkpoint 디렉터리를 찾을 수 없습니다: {args.resume_from_checkpoint}"
        )
    if (
        output.exists()
        and any(output.iterdir())
        and args.resume_from_checkpoint is None
        and not args.overwrite_output_dir
    ):
        raise DataValidationError(
            f"출력 디렉터리가 비어 있지 않습니다: {output}. "
            "이어하려면 --resume-from-checkpoint, 덮어쓰기를 허용하려면 --overwrite-output-dir를 사용하세요."
        )


def atomic_write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    os.replace(temporary, path)


def atomic_write_jsonl(path: Path, values: Sequence[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8") as target:
        for value in values:
            target.write(
                json.dumps(value, ensure_ascii=False, separators=(",", ":")) + "\n"
            )
        target.flush()
        os.fsync(target.fileno())
    os.replace(temporary, path)


def rename_metric_prefix(
    metrics: dict[str, float | int], old_prefix: str, new_prefix: str
) -> dict[str, float | int]:
    return {
        (
            new_prefix + key[len(old_prefix) :]
            if key.startswith(old_prefix)
            else key
        ): value
        for key, value in metrics.items()
    }


def run_training(
    args: argparse.Namespace,
    data_path: Path,
    train_records: list[TrainingRecord],
    evaluation_records: list[TrainingRecord],
    split_metadata: dict[str, Any],
    *,
    evaluation_role: str = "test",
) -> dict[str, Any]:
    stack = import_training_stack()
    torch = stack["torch"]
    if not torch.cuda.is_available():
        raise RuntimeError("Qwen3-4B 추가학습에는 CUDA GPU가 필요합니다.")

    local_rank = int(os.environ.get("LOCAL_RANK", args.local_rank if args.local_rank >= 0 else 0))
    rank = int(os.environ.get("RANK", "0"))
    world_size = int(os.environ.get("WORLD_SIZE", "1"))
    if local_rank >= torch.cuda.device_count():
        raise RuntimeError(
            f"LOCAL_RANK={local_rank}이지만 사용 가능한 GPU는 {torch.cuda.device_count()}개입니다."
        )
    torch.cuda.set_device(local_rank)
    stack["set_seed"](args.seed)
    if rank != 0:
        # Seven identical model-loading progress bars and third-party
        # deprecation warnings make tee'd tmux logs needlessly unreadable.
        stack["transformers_logging"].disable_progress_bar()
        stack["transformers_logging"].set_verbosity_error()
        warnings.filterwarnings(
            "ignore", category=FutureWarning, module=r"bitsandbytes(?:\..*)?"
        )
        warnings.filterwarnings(
            "ignore",
            category=FutureWarning,
            message=r"`torch\.distributed\.all_gather_into_tensor` is deprecated.*",
        )

    dtype_argument = (
        "dtype" if parse_version(stack["transformers_version"]) >= (5,) else "torch_dtype"
    )
    model_kwargs: dict[str, Any] = {
        "revision": args.revision,
        dtype_argument: torch.float16,
        "device_map": {"": local_rank},
        "low_cpu_mem_usage": True,
    }
    if args.attn_implementation:
        model_kwargs["attn_implementation"] = args.attn_implementation
    if args.use_4bit:
        model_kwargs["quantization_config"] = stack["BitsAndBytesConfig"](
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )

    tokenizer = stack["AutoTokenizer"].from_pretrained(
        args.model, revision=args.revision, use_fast=True
    )
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    if rank == 0:
        print(f"[model] {args.model} (revision={args.revision})", file=sys.stderr)
        print(f"[device] GPU {local_rank}, world_size={world_size}, fp16", file=sys.stderr)
    model = stack["AutoModelForCausalLM"].from_pretrained(args.model, **model_kwargs)
    model.config.use_cache = False
    if "logits_to_keep" not in inspect.signature(model.forward).parameters:
        raise RuntimeError(
            "현재 모델 forward가 logits_to_keep를 지원하지 않습니다. "
            "Qwen3 및 transformers>=4.51 조합인지 확인하세요."
        )
    model.loss_function = make_chunked_causal_lm_loss(torch, args.loss_chunk_size)
    if args.use_4bit:
        model = stack["prepare_model_for_kbit_training"](
            model,
            use_gradient_checkpointing=args.gradient_checkpointing,
            gradient_checkpointing_kwargs={"use_reentrant": False},
        )
    elif args.gradient_checkpointing:
        model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
        model.enable_input_require_grads()

    lora_config = stack["LoraConfig"](
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=LORA_TARGET_MODULES,
    )
    model = stack["get_peft_model"](model, lora_config)
    if rank == 0:
        model.print_trainable_parameters()
        print(
            f"[memory] attention={args.attn_implementation}, "
            f"assistant-only logits, loss chunk={args.loss_chunk_size} tokens",
            file=sys.stderr,
        )

    encoded_train, train_lengths = encode_records(
        train_records, tokenizer, args.max_seq_length
    )
    encoded_evaluation, evaluation_lengths = encode_records(
        evaluation_records, tokenizer, args.max_seq_length
    )
    if rank == 0:
        all_lengths = train_lengths + evaluation_lengths
        print(
            f"[tokens] min={min(all_lengths)}, p50={percentile(all_lengths, 0.50)}, "
            f"p95={percentile(all_lengths, 0.95)}, max={max(all_lengths)}",
            file=sys.stderr,
        )

    samples_per_process = math.ceil(len(train_records) / world_size)
    batches_per_process = math.ceil(samples_per_process / args.batch_size)
    updates_per_epoch = max(
        1, math.ceil(batches_per_process / args.gradient_accumulation_steps)
    )
    total_training_steps = math.ceil(updates_per_epoch * args.epochs)
    warmup_steps = math.ceil(total_training_steps * args.warmup_ratio)
    if rank == 0:
        print(
            f"[train] optimizer steps={total_training_steps:,} "
            f"({updates_per_epoch:,}/epoch) · warmup steps={warmup_steps:,}",
            file=sys.stderr,
        )

    training_argument_names = inspect.signature(stack["TrainingArguments"]).parameters
    compatibility_args: dict[str, Any] = {}
    if "overwrite_output_dir" in training_argument_names:
        compatibility_args["overwrite_output_dir"] = args.overwrite_output_dir
    if "save_safetensors" in training_argument_names:
        compatibility_args["save_safetensors"] = True

    training_args = stack["TrainingArguments"](
        output_dir=str(args.output_dir),
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.test_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        lr_scheduler_type="cosine",
        warmup_steps=warmup_steps,
        weight_decay=args.weight_decay,
        max_grad_norm=0.3,
        fp16=True,
        bf16=False,
        gradient_checkpointing=args.gradient_checkpointing,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        optim="paged_adamw_8bit" if args.use_4bit else "adamw_torch_fused",
        logging_strategy="steps",
        logging_steps=args.logging_steps,
        logging_first_step=True,
        eval_strategy="no",
        save_strategy="epoch",
        save_total_limit=args.save_total_limit,
        load_best_model_at_end=False,
        prediction_loss_only=True,
        report_to="none",
        seed=args.seed,
        data_seed=args.seed,
        dataloader_num_workers=args.dataloader_num_workers,
        ddp_find_unused_parameters=False if world_size > 1 else None,
        remove_unused_columns=False,
        **compatibility_args,
    )
    data_collator = make_collator(torch, tokenizer.pad_token_id)
    trainer = stack["Trainer"](
        model=model,
        args=training_args,
        train_dataset=EncodedDataset(encoded_train),
        data_collator=data_collator,
        processing_class=tokenizer,
    )
    result = trainer.train(
        resume_from_checkpoint=(
            str(args.resume_from_checkpoint) if args.resume_from_checkpoint is not None else None
        )
    )
    # Evaluation records are never passed to Trainer and cannot affect updates.
    gc.collect()
    torch.cuda.empty_cache()
    evaluation_model = trainer.accelerator.unwrap_model(trainer.model_wrapped)
    teacher_forced_raw = evaluate_test_metrics(
        torch=torch,
        model=evaluation_model,
        encoded_test=encoded_evaluation,
        data_collator=data_collator,
        device=torch.device("cuda", local_rank),
        rank=rank,
        world_size=world_size,
        batch_size=args.test_batch_size,
    )
    teacher_forced_metrics = rename_metric_prefix(
        teacher_forced_raw, "test_", f"{evaluation_role}_"
    )
    evaluation_metrics: dict[str, float | int] = dict(teacher_forced_metrics)
    generation_predictions: list[dict[str, Any]] = []
    if args.generation_eval:
        generation_raw, generation_predictions = evaluate_generation_metrics(
            torch=torch,
            model=evaluation_model,
            tokenizer=tokenizer,
            records=evaluation_records,
            system_prompt=SYSTEM_PROMPT,
            device=torch.device("cuda", local_rank),
            rank=rank,
            world_size=world_size,
            batch_size=args.generation_batch_size,
            max_new_tokens=args.generation_max_new_tokens,
        )
        evaluation_metrics.update(
            {
                f"{evaluation_role}_{key}": value
                for key, value in generation_raw.items()
            }
        )
    trainer.log(evaluation_metrics)
    if trainer.is_world_process_zero():
        print(
            f"[{evaluation_role}] loss="
            f"{evaluation_metrics[f'{evaluation_role}_loss']:.6f} · "
            f"accuracy={evaluation_metrics[f'{evaluation_role}_accuracy']:.2%} · "
            f"teacher-forced exact="
            f"{evaluation_metrics[f'{evaluation_role}_teacher_forced_exact_match']:.2%} · "
            f"tokens={evaluation_metrics[f'{evaluation_role}_correct_tokens']:,}/"
            f"{evaluation_metrics[f'{evaluation_role}_supervised_tokens']:,} · "
            f"exact={evaluation_metrics[f'{evaluation_role}_exact_match_count']:,}/"
            f"{evaluation_metrics[f'{evaluation_role}_samples']:,} · "
            f"runtime={evaluation_metrics.get(f'{evaluation_role}_runtime', float('nan')):.2f}s",
            file=sys.stderr,
        )
        if args.generation_eval:
            print(
                f"[{evaluation_role}-generation] valid="
                f"{evaluation_metrics[f'{evaluation_role}_generation_valid_rate']:.2%} · "
                f"strict="
                f"{evaluation_metrics[f'{evaluation_role}_generation_strict_exact_match']:.2%} · "
                f"order-insensitive="
                f"{evaluation_metrics[f'{evaluation_role}_generation_order_insensitive_exact_match']:.2%} · "
                f"normalized="
                f"{evaluation_metrics[f'{evaluation_role}_generation_normalized_exact_match']:.2%}",
                file=sys.stderr,
            )
    trainer.save_model(str(args.output_dir))
    trainer.save_state()

    training_metrics = dict(result.metrics)
    resolved_revision = getattr(model.config, "_commit_hash", None) or args.revision
    manifest: dict[str, Any] = {
        "base_model": args.model,
        "requested_revision": args.revision,
        "resolved_revision": resolved_revision,
        "data_path": str(data_path),
        "data_sha256": sha256_file(data_path),
        "record_count": len(train_records) + len(evaluation_records),
        "train_count": len(train_records),
        f"{evaluation_role}_count": len(evaluation_records),
        "train_cve_ids": [record.cve_id for record in train_records],
        f"{evaluation_role}_cve_ids": [
            record.cve_id for record in evaluation_records
        ],
        "evaluation_role": evaluation_role,
        "split": split_metadata,
        "system_prompt": SYSTEM_PROMPT,
        "target_shape": {"bindings": "list[binding]"},
        "lora_target_modules": LORA_TARGET_MODULES,
        "cli_args": {
            key: str(value) if isinstance(value, Path) else value
            for key, value in vars(args).items()
        },
        "training_metrics": training_metrics,
        f"{evaluation_role}_metrics": evaluation_metrics,
        "metric_definitions": {
            "accuracy": "micro next-token accuracy over gold assistant JSON tokens",
            "teacher_forced_exact_match": (
                "fraction of records whose complete assistant answer is token-perfect "
                "while conditioning on the gold prefix"
            ),
            "generation_strict_exact_match": (
                "greedy free-generation payload equals the labeled JSON structure"
            ),
            "generation_order_insensitive_exact_match": (
                "free-generation exact match after sorting bindings and version ranges"
            ),
            "generation_normalized_exact_match": (
                "order-insensitive free-generation exact match after case/punctuation "
                "normalization of string fields"
            ),
            "aggregation": (
                "each DDP rank evaluates a unique unpadded shard; scalar counts are summed"
            ),
        },
        "packages": {
            name: package_version(name)
            for name in ["torch", "transformers", "accelerate", "peft", "bitsandbytes"]
        },
    }
    if trainer.is_world_process_zero():
        tokenizer.save_pretrained(args.output_dir)
        atomic_write_json(args.output_dir / "training_manifest.json", manifest)
        if args.generation_eval:
            atomic_write_jsonl(
                args.output_dir / f"{evaluation_role}_predictions.jsonl",
                generation_predictions,
            )
        print(f"완료: LoRA adapter와 tokenizer를 저장했습니다: {args.output_dir}")

    if torch.distributed.is_available() and torch.distributed.is_initialized():
        torch.distributed.barrier(device_ids=[local_rank])
    if hasattr(trainer.accelerator, "free_memory"):
        trainer.accelerator.free_memory()
    del evaluation_model, trainer, model, tokenizer, data_collator
    gc.collect()
    torch.cuda.empty_cache()
    return {
        "training_metrics": training_metrics,
        "evaluation_metrics": evaluation_metrics,
        "manifest": manifest,
    }


def metric_summary(values: Sequence[float]) -> dict[str, float]:
    mean = sum(values) / len(values)
    variance = sum((value - mean) ** 2 for value in values) / len(values)
    return {
        "mean": mean,
        "std": math.sqrt(variance),
        "min": min(values),
        "max": max(values),
    }


def aggregate_cv_metrics(
    fold_results: Sequence[dict[str, Any]],
) -> dict[str, Any]:
    metrics = [result["evaluation_metrics"] for result in fold_results]
    keys = sorted(
        {
            key
            for fold_metrics in metrics
            for key, value in fold_metrics.items()
            if isinstance(value, (int, float))
            and not isinstance(value, bool)
            and (
                key.endswith("_rate")
                or key.endswith("_match")
                or key.endswith("_accuracy")
                or key.endswith("_loss")
            )
        }
    )
    macro = {
        key: metric_summary([float(fold_metrics[key]) for fold_metrics in metrics])
        for key in keys
        if all(key in fold_metrics for fold_metrics in metrics)
    }
    supervised_tokens = sum(
        int(item["validation_supervised_tokens"]) for item in metrics
    )
    validation_samples = sum(int(item["validation_samples"]) for item in metrics)
    micro: dict[str, float | int] = {
        "validation_samples": validation_samples,
        "validation_supervised_tokens": supervised_tokens,
        "validation_loss": sum(
            float(item["validation_loss"])
            * int(item["validation_supervised_tokens"])
            for item in metrics
        )
        / supervised_tokens,
        "validation_accuracy": sum(
            int(item["validation_correct_tokens"]) for item in metrics
        )
        / supervised_tokens,
        "validation_teacher_forced_exact_match": sum(
            int(item["validation_exact_match_count"]) for item in metrics
        )
        / validation_samples,
    }
    if all("validation_generation_samples" in item for item in metrics):
        generation_samples = sum(
            int(item["validation_generation_samples"]) for item in metrics
        )
        micro.update(
            {
                "validation_generation_samples": generation_samples,
                "validation_generation_valid_rate": sum(
                    int(item["validation_generation_valid_count"])
                    for item in metrics
                )
                / generation_samples,
                "validation_generation_strict_exact_match": sum(
                    int(item["validation_generation_strict_exact_count"])
                    for item in metrics
                )
                / generation_samples,
                "validation_generation_order_insensitive_exact_match": sum(
                    int(
                        item[
                            "validation_generation_order_insensitive_exact_count"
                        ]
                    )
                    for item in metrics
                )
                / generation_samples,
                "validation_generation_normalized_exact_match": sum(
                    int(item["validation_generation_normalized_exact_count"])
                    for item in metrics
                )
                / generation_samples,
            }
        )
    return {"macro_fold_statistics": macro, "micro_oof": micro}


def run_cross_validation(
    *,
    args: argparse.Namespace,
    data_path: Path,
    development_records: list[TrainingRecord],
    locked_test_records: list[TrainingRecord],
    outer_split_metadata: dict[str, Any],
    folds: Sequence[CVFold],
    cv_metadata: dict[str, Any],
) -> None:
    if args.resume_from_checkpoint is not None:
        raise DataValidationError(
            "--resume-from-checkpoint는 단일 학습에서만 지원됩니다. "
            "CV 재실행은 새 output-dir를 사용하세요."
        )
    root_output = args.output_dir.resolve()
    fold_results: list[dict[str, Any]] = []
    rank = int(os.environ.get("RANK", "0"))
    for fold in folds:
        fold_args = argparse.Namespace(**vars(args))
        fold_args.output_dir = root_output / f"fold-{fold.index:02d}"
        fold_args.seed = args.seed + fold.index
        fold_args.resume_from_checkpoint = None
        ensure_output_is_safe(fold_args)
        if rank == 0:
            print(
                f"[cv] fold {fold.index}/{len(folds)} · "
                f"train {len(fold.train_records):,} / "
                f"validation {len(fold.validation_records):,} · "
                f"output={fold_args.output_dir}",
                file=sys.stderr,
            )
        result = run_training(
            fold_args,
            data_path,
            list(fold.train_records),
            list(fold.validation_records),
            {
                "outer_split": outer_split_metadata,
                "cross_validation": cv_metadata,
                "fold": fold.metadata,
                "locked_test_evaluated": False,
            },
            evaluation_role="validation",
        )
        fold_results.append(result)

    if rank == 0:
        aggregate = aggregate_cv_metrics(fold_results)
        fold_summaries = [
            {
                "fold_index": fold.index,
                "output_dir": str((root_output / f"fold-{fold.index:02d}").resolve()),
                "train_count": len(fold.train_records),
                "validation_count": len(fold.validation_records),
                "training_metrics": result["training_metrics"],
                "validation_metrics": result["evaluation_metrics"],
            }
            for fold, result in zip(folds, fold_results)
        ]
        cv_manifest = {
            "mode": "stratified_product_group_cross_validation",
            "base_model": args.model,
            "requested_revision": args.revision,
            "data_path": str(data_path),
            "data_sha256": sha256_file(data_path),
            "record_count": len(development_records) + len(locked_test_records),
            "development_count": len(development_records),
            "locked_test_count": len(locked_test_records),
            "locked_test_evaluated": False,
            "development_cve_ids": [
                record.cve_id for record in development_records
            ],
            "locked_test_cve_ids": [
                record.cve_id for record in locked_test_records
            ],
            "outer_split": outer_split_metadata,
            "cross_validation": cv_metadata,
            "folds": fold_summaries,
            "aggregate_metrics": aggregate,
            "system_prompt": SYSTEM_PROMPT,
            "cli_args": {
                key: str(value) if isinstance(value, Path) else value
                for key, value in vars(args).items()
            },
        }
        atomic_write_json(root_output / "cv_manifest.json", cv_manifest)
        if args.generation_eval:
            oof_predictions: list[dict[str, Any]] = []
            for fold in folds:
                prediction_path = (
                    root_output
                    / f"fold-{fold.index:02d}"
                    / "validation_predictions.jsonl"
                )
                with prediction_path.open("r", encoding="utf-8") as source:
                    for line in source:
                        prediction = json.loads(line)
                        prediction["fold_index"] = fold.index
                        oof_predictions.append(prediction)
            oof_predictions.sort(key=lambda item: item["cve_id"])
            if len(oof_predictions) != len(development_records) or len(
                {item["cve_id"] for item in oof_predictions}
            ) != len(development_records):
                raise RuntimeError("OOF prediction에 development 레코드 누락/중복이 있습니다.")
            atomic_write_jsonl(
                root_output / "oof_predictions.jsonl", oof_predictions
            )
        micro = aggregate["micro_oof"]
        message = (
            f"[cv-summary] teacher-forced exact="
            f"{micro['validation_teacher_forced_exact_match']:.2%}"
        )
        if "validation_generation_normalized_exact_match" in micro:
            message += (
                " · generation normalized exact="
                f"{micro['validation_generation_normalized_exact_match']:.2%}"
            )
        print(message, file=sys.stderr)
        print(
            f"완료: {len(folds)}-fold CV 결과를 저장했습니다: {root_output} "
            "(locked test는 평가하지 않음)"
        )


def default_data_path() -> Path:
    return Path("data/cve_bindings_merged-800-hardrule-v1.jsonl")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="일관화·병합된 CVE binding JSONL로 Qwen3-4B QLoRA 추가학습"
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=default_data_path(),
        help="학습 JSONL 경로 (기본: data/cve_bindings_merged-800-hardrule-v1.jsonl)",
    )
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Hugging Face model ID 또는 로컬 경로")
    parser.add_argument("--revision", default="main", help="모델 revision/commit (기본: main)")
    parser.add_argument(
        "--output-dir", type=Path, default=Path("models/qwen3-4b-cve-bindings-lora")
    )
    parser.add_argument(
        "--split-ratio",
        type=int,
        nargs=2,
        default=(9, 1),
        metavar=("TRAIN", "TEST"),
        help="train/test 정수 비율 (기본: 9 1)",
    )
    parser.add_argument(
        "--cv-folds",
        type=int,
        default=1,
        help="1이면 기존 단일 9:1 학습, 2 이상이면 development 내부 Stratified Group K-fold (권장: 5)",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-seq-length", type=int, default=5120)
    parser.add_argument("--epochs", type=float, default=5.0)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument(
        "--test-batch-size",
        type=int,
        default=1,
        help="학습 종료 후 held-out test 평가의 GPU당 batch 크기 (기본: 1)",
    )
    parser.add_argument(
        "--generation-eval",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="평가 split에 greedy 자유 생성 exact/schema 지표 측정 (기본: 사용)",
    )
    parser.add_argument(
        "--generation-batch-size",
        type=int,
        default=1,
        help="자유 생성 평가의 GPU당 batch 크기 (기본: 1)",
    )
    parser.add_argument(
        "--generation-max-new-tokens",
        type=int,
        default=1024,
        help="자유 생성 평가의 최대 출력 token 수 (기본: 1024)",
    )
    parser.add_argument("--gradient-accumulation-steps", type=int, default=8)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--warmup-ratio", type=float, default=0.1)
    parser.add_argument("--weight-decay", type=float, default=0.01)
    parser.add_argument("--lora-rank", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=32)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument("--logging-steps", type=int, default=1)
    parser.add_argument("--save-total-limit", type=int, default=2)
    parser.add_argument("--dataloader-num-workers", type=int, default=0)
    parser.add_argument(
        "--attn-implementation",
        choices=["eager", "sdpa", "flash_attention_2"],
        default="sdpa",
    )
    parser.add_argument(
        "--loss-chunk-size",
        type=int,
        default=64,
        help="float32 cross-entropy를 계산할 token 묶음 크기 (기본: 64)",
    )
    parser.add_argument(
        "--use-4bit", action=argparse.BooleanOptionalAction, default=True, help="NF4 QLoRA 사용"
    )
    parser.add_argument(
        "--gradient-checkpointing",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    parser.add_argument("--resume-from-checkpoint", type=Path)
    parser.add_argument("--overwrite-output-dir", action="store_true")
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="의존성/모델을 불러오지 않고 JSONL 스키마와 split만 검사",
    )
    parser.add_argument("--local-rank", "--local_rank", type=int, default=-1, help=argparse.SUPPRESS)
    return parser.parse_args()


def validate_cli_args(args: argparse.Namespace) -> None:
    positive_values = {
        "--max-seq-length": args.max_seq_length,
        "--epochs": args.epochs,
        "--batch-size": args.batch_size,
        "--test-batch-size": args.test_batch_size,
        "--generation-batch-size": args.generation_batch_size,
        "--generation-max-new-tokens": args.generation_max_new_tokens,
        "--gradient-accumulation-steps": args.gradient_accumulation_steps,
        "--learning-rate": args.learning_rate,
        "--lora-rank": args.lora_rank,
        "--lora-alpha": args.lora_alpha,
        "--logging-steps": args.logging_steps,
        "--save-total-limit": args.save_total_limit,
        "--loss-chunk-size": args.loss_chunk_size,
    }
    invalid = [name for name, value in positive_values.items() if value <= 0]
    if invalid:
        raise DataValidationError(f"0보다 커야 하는 인자: {', '.join(invalid)}")
    if any(value <= 0 for value in args.split_ratio):
        raise DataValidationError("--split-ratio의 두 값은 모두 0보다 커야 합니다.")
    if args.cv_folds < 1:
        raise DataValidationError("--cv-folds는 1 이상이어야 합니다.")
    if not 0.0 <= args.warmup_ratio < 1.0:
        raise DataValidationError("--warmup-ratio는 0 이상 1 미만이어야 합니다.")
    if not 0.0 <= args.lora_dropout < 1.0:
        raise DataValidationError("--lora-dropout은 0 이상 1 미만이어야 합니다.")


def cleanup_distributed_after_failure() -> None:
    """Release NCCL state when training exits before its normal synchronization."""
    torch = sys.modules.get("torch")
    distributed = getattr(torch, "distributed", None) if torch is not None else None
    if (
        distributed is not None
        and distributed.is_available()
        and distributed.is_initialized()
    ):
        try:
            # Do not barrier here: another rank may already have failed or been
            # terminated by torchrun, which would turn cleanup into a hang.
            distributed.destroy_process_group()
        except RuntimeError:
            pass


def main() -> int:
    args = parse_args()
    try:
        validate_cli_args(args)
        data_path = args.data.resolve()
        records = load_records(data_path)
        empty_count = sum(not record.bindings for record in records)
        rank = int(os.environ.get("RANK", "0"))
        if args.cv_folds > 1:
            development_records, locked_test_records, outer_metadata = (
                split_development_test_grouped(
                    records, tuple(args.split_ratio), args.seed
                )
            )
            folds, cv_metadata = make_cv_folds(
                development_records, args.cv_folds, args.seed
            )
            if rank == 0:
                fold_counts = ", ".join(
                    f"{fold.index}:{len(fold.train_records)}/"
                    f"{len(fold.validation_records)}"
                    for fold in folds
                )
                print(
                    f"[data] 전체 {len(records):,}건 (빈 binding {empty_count:,}건) · "
                    f"development {len(development_records):,} / "
                    f"locked test {len(locked_test_records):,} · "
                    f"{args.cv_folds}-fold train/validation={fold_counts} · "
                    f"seed {args.seed}",
                    file=sys.stderr,
                )
            if args.validate_only:
                if rank == 0:
                    print(
                        "검증 완료: JSONL 스키마, grouped 9:1 split, "
                        f"{args.cv_folds}-fold Stratified Group CV가 정상입니다."
                    )
                return 0
            ensure_output_is_safe(args)
            run_cross_validation(
                args=args,
                data_path=data_path,
                development_records=development_records,
                locked_test_records=locked_test_records,
                outer_split_metadata=outer_metadata,
                folds=folds,
                cv_metadata=cv_metadata,
            )
        else:
            train_records, test_records, split_metadata = split_train_test(
                records, tuple(args.split_ratio), args.seed
            )
            if rank == 0:
                print(
                    f"[data] 전체 {len(records):,}건 (빈 binding {empty_count:,}건) · "
                    f"train {len(train_records):,} / test {len(test_records):,} · "
                    f"ratio {args.split_ratio[0]}:{args.split_ratio[1]} · "
                    f"seed {args.seed}",
                    file=sys.stderr,
                )
            if args.validate_only:
                if rank == 0:
                    print(
                        "검증 완료: JSONL 스키마, CVE ID 중복, "
                        "train/test split이 정상입니다."
                    )
                return 0
            ensure_output_is_safe(args)
            run_training(
                args,
                data_path,
                train_records,
                test_records,
                split_metadata,
                evaluation_role="test",
            )
    except (DataValidationError, OSError, RuntimeError, ValueError) as exc:
        print(f"오류: {exc}", file=sys.stderr)
        return 1
    finally:
        cleanup_distributed_after_failure()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
